moveit_servo:
  ros__parameters:

    use_gazebo: false

    status_topic: ~/status

    cartesian_command_in_topic: ~/delta_twist_cmds

    joint_command_in_topic: ~/delta_joint_cmds

    command_out_topic: /joint_trajectory_controller/joint_trajectory

    publish_period: 0.02

    low_latency_mode: true

    command_in_type: "unitless"

    publish_joint_positions: true
    publish_joint_velocities: false
    publish_joint_accelerations: false

    smoothing_filter_plugin_name: "online_signal_smoothing::ButterworthFilterPlugin"

    move_group_name: right_arm

    planning_frame: world

    ee_frame_name: right_panda_hand

    robot_link_command_frame: right_panda_hand

    incoming_command_timeout: 0.1

    linear_scale: 0.2
    rotational_scale: 0.2
    joint_scale: 0.2

    collision_check_rate: 10.0

    self_collision_proximity_threshold: 0.01
    scene_collision_proximity_threshold: 0.02